spring.profiles.include:
  - database-tourism
  - redis
---
spring.config.activate.on-profile: local
server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret-access-token: ${JWT_SECRET_ACCESS_TOKEN}
file:
  upload-dir: /Users/kimyoungjae/desktop/file/
  #upload-dir: /Users/yjkim-mtn/desktop/

---
spring.config.activate.on-profile: prod
server:
  port: 18080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-access-token: ${JWT_SECRET_ACCESS_TOKEN}
file:
  upload-dir: /app/tour/files/