spring.profiles.include:
  - database-agriculture
  - redis
---
spring.config.activate.on-profile: local
server:
  port: 8081
open-api:
  key: ${OPEN_API_KEY}
file:
  uploadPath: ${FILE_UPLOAD_PATH}
  url: ${FILE_URL}
aes:
  key: ${AES_KEY}
  iv: ${AES_IV}
fcm:
  key: ${FCM_KEY}
spring:
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


---
spring.config.activate.on-profile: prod
server:
  port: 7000
open-api:
  key: ${OPEN_API_KEY}
file:
  uploadPath: ${FILE_UPLOAD_PATH}
  url: ${FILE_URL}
aes:
  key: ${AES_KEY}
  iv: ${AES_IV}
fcm:
  key: ${FCM_KEY}
spring:
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
