spring.profiles.include:
  - database-agriculture
  - redis
---
spring.config.activate.on-profile: local
server:
  port: 8081
open-api:
  key: ${OPEN_API_KEY}
file:
  uploadPath: ${FILE_UPLOAD_PATH}
  url: ${FILE_URL}
aes:
  key: ${AES_KEY}
  iv: ${AES_IV}


---
spring.config.activate.on-profile: prod
server:
  port: 7000
open-api:
  key: ${OPEN_API_KEY}
file:
  uploadPath: ${FILE_UPLOAD_PATH}
  url: ${FILE_URL}
aes:
  key: ${AES_KEY}
  iv: ${AES_IV}
