spring.profiles.include:
  - database-agriculture
  - redis
---
spring.config.activate.on-profile: local
server:
  port: 8081
open-api:
  key: ${OPEN_API_KEY}


---
spring.config.activate.on-profile: prod
server:
  port: 7000
open-api:
  key: ${OPEN_API_KEY}
