spring:
  datasource:
    url: jdbc:mysql://144.24.95.101:3306/tourism?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
---
spring.config.activate.on-profile: local
spring:
  datasource:
    password: ${MOTIVATION_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
---
spring.config.activate.on-profile: prod
spring:
  datasource:
    password: ${MOTIVATION_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

