spring.profiles.include:
  - database-gyeongnam
  - redis
---
spring.config.activate.on-profile: local
server:
  port: 8080
jwt:
  secret-access-token: ${JWT_SECRET_ACCESS_TOKEN}

---
spring.config.activate.on-profile: prod
server:
  port: 8080
jwt:
  secret-access-token: ${JWT_SECRET_ACCESS_TOKEN}